source scripts instead of executing them

diff --git a/libexec/kessel/workflows/spack/prepare_env b/libexec/kessel/workflows/spack/prepare_env
--- a/libexec/kessel/workflows/spack/prepare_env
+++ b/libexec/kessel/workflows/spack/prepare_env
@@ -2,18 +2,15 @@
 #KESSEL title: Prepare Environment
 #KESSEL collapsed: true
 
-source $KESSEL_ROOT/share/kessel/setup-env.sh
-
-set -e
-
 if [ -z "$KESSEL_SYSTEM" ] || [ -z "$KESSEL_PROJECT_SPEC" ]; then
-  echo "ERROR: Invalid state" >&2
-  exit 1
+  echo "ERROR: Invalid state '$KESSEL_SYSTEM' '$KESSEL_PROJECT_SPEC' " >&2
+  false
+  return
 fi
 
-kessel_export KESSEL_ENVIRONMENT="${KESSEL_ENVIRONMENT:-default}"
-kessel_export KESSEL_SOURCE_DIR="${KESSEL_INSTALL_DIR:-$PWD}"
-kessel_export KESSEL_BINARY_DIR="${KESSEL_INSTALL_DIR:-$KESSEL_SOURCE_DIR/build}"
+export KESSEL_ENVIRONMENT="${KESSEL_ENVIRONMENT:-default}"
+export KESSEL_SOURCE_DIR="${KESSEL_SOURCE_DIR:-$PWD}"
+export KESSEL_BUILD_DIR="${KESSEL_BUILD_DIR:-$KESSEL_SOURCE_DIR/build}"
 
 TEMP=""
 while (( "$#" )); do
@@ -24,7 +21,7 @@ while (( "$#" )); do
       ;;
     -e|--env)
       if [ -n "$2" ] && [[ "$2" != -* ]]; then
-         kessel_export KESSEL_ENVIRONMENT="$2"
+         export KESSEL_ENVIRONMENT="$2"
          shift 2
       else
          echo "ERROR: -S/--source-dir requires an argument." >&2
@@ -33,12 +30,12 @@ while (( "$#" )); do
       ;;
     --env=*)
       value="${1#*=}"
-      kessel_export KESSEL_ENVIRONMENT="$value"
+      export KESSEL_ENVIRONMENT="$value"
       shift
       ;;
     -S|--source-dir)
       if [ -n "$2" ] && [[ "$2" != -* ]]; then
-         kessel_export KESSEL_SOURCE_DIR="$2"
+         export KESSEL_SOURCE_DIR="$2"
          shift 2
       else
          echo "ERROR: -S/--source-dir requires an argument." >&2
@@ -47,12 +44,12 @@ while (( "$#" )); do
       ;;
     --source-dir=*)
       value="${1#*=}"
-      kessel_export KESSEL_INSTALL_DIR="$value"
+      export KESSEL_INSTALL_DIR="$value"
       shift
       ;;
     -B|--build-dir)
       if [ -n "$2" ] && [[ "$2" != -* ]]; then
-         kessel_export KESSEL_BUILD_DIR="$2"
+         export KESSEL_BUILD_DIR="$2"
          shift 2
       else
          echo "ERROR: -B/--build-dir requires an argument." >&2
@@ -61,7 +58,7 @@ while (( "$#" )); do
       ;;
     --build-dir=*)
       value="${1#*=}"
-      kessel_export KESSEL_BUILD_DIR="$value"
+      export KESSEL_BUILD_DIR="$value"
       shift
       ;;
     -*|--*)
@@ -76,7 +73,7 @@ while (( "$#" )); do
 done
 
 if [ "$TEMP" ]; then
-  kessel_export KESSEL_PROJECT_SPEC="$TEMP"
+  export KESSEL_PROJECT_SPEC="$TEMP"
 fi
 
 if ! kessel env activate "$KESSEL_ENVIRONMENT"; then
@@ -91,9 +88,11 @@ if ! kessel env activate "$KESSEL_ENVIRONMENT"; then
   fi
 fi
 
-if [ -d "$source_dir/spack_repo/$project" ]; then
-  spack repo remove $project 2> /dev/null > /dev/null || true
-  spack repo add $source_dir/spack_repo/$project
+export KESSEL_PROJECT_NAME=$(spack-python -c "spec = spack.spec.Spec('$KESSEL_PROJECT_SPEC');print(spec.name)")
+
+if [ -d "$KESSEL_SOURCE_DIR/spack_repo/$KESSEL_PROJECT_NAME" ]; then
+  spack repo remove "$KESSEL_PROJECT_NAME" 2> /dev/null > /dev/null || true
+  spack repo add "$KESSEL_SOURCE_DIR/spack_repo/$KESSEL_PROJECT_NAME"
 fi
 
 PROJECT_PREFERRED_VERSION=$(spack-python -c "\
@@ -101,6 +100,6 @@ spec = spack.spec.Spec('$KESSEL_PROJECT_SPEC');\
 pkg_cls = spack.repo.PATH.get_pkg_class(spec.fullname);\
 preferred_version = spec.versions if (spack.version.ver(':') not in spec.versions) else spack.package_base.preferred_version(pkg_cls(spec));\
 print(preferred_version)")
-PROJECT_NAME=$(spack-python -c "spec = spack.spec.Spec('$KESSEL_PROJECT_SPEC');print(spec.name)")
 
-spack develop -b "$KESSEL_BUILD_DIR" -p "$KESSEL_SOURCE_DIR" --no-clone "$PROJECT_NAME@$PROJECT_PREFERRED_VERSION"
+
+spack develop -b "$KESSEL_BUILD_DIR" -p "$KESSEL_SOURCE_DIR" --no-clone "$KESSEL_PROJECT_NAME@$PROJECT_PREFERRED_VERSION"
diff --git a/libexec/kessel/workflows/spack/setup b/libexec/kessel/workflows/spack/setup
--- a/libexec/kessel/workflows/spack/setup
+++ b/libexec/kessel/workflows/spack/setup
@@ -2,47 +2,50 @@
 #KESSEL title: Setup
 #KESSEL collapsed: true
 
-kessel_export KESSEL_SYSTEM="${KESSEL_SYSTEM:-local}"
-kessel_export KESSEL_WORKFLOW_DEPLOYMENT="${KESSEL_WORKFLOW_DEPLOYMENT:-${TMPDIR:-/tmp}/$USER-ci-envs}"
+export KESSEL_SYSTEM="${KESSEL_SYSTEM:-local}"
+export KESSEL_WORKFLOW_DEPLOYMENT="${KESSEL_WORKFLOW_DEPLOYMENT:-${TMPDIR:-/tmp}/$USER-ci-envs}"
 
 TEMP=()
 while (( "$#" )); do
   case "$1" in
     -h|--help)
       usage
-      exit 0
+      return
       ;;
     -D|--deployment)
       if [ -n "$2" ] && [[ "$2" != -* ]]; then
-         kessel_export KESSEL_WORKFLOW_DEPLOYMENT="$2"
+         export KESSEL_WORKFLOW_DEPLOYMENT="$2"
          shift 2
       else
          echo "ERROR: -I/--install-dir requires an argument." >&2
-         exit 1
+         false
+         return
       fi
       ;;
     --deployment=*)
       value="${1#*=}"
-      kessel_export KESSEL_WORKFLOW_DEPLOYMENT="$value"
+      export KESSEL_WORKFLOW_DEPLOYMENT="$value"
       shift
       ;;
     -s|--system)
       if [ -n "$2" ] && [[ "$2" != -* ]]; then
-         kessel_export KESSEL_SYSTEM="$2"
+         export KESSEL_SYSTEM="$2"
          shift 2
       else
-         echo "ERROR: -I/--install-dir requires an argument." >&2
-         exit 1
+         echo "ERROR: -s/--system requires an argument." >&2
+         false
+         return
       fi
       ;;
     --system=*)
       value="${1#*=}"
-      kessel_export KESSEL_SYSTEM="$value"
+      export KESSEL_SYSTEM="$value"
       shift
       ;;
     -*|--*)
       echo "ERROR: invalid option $1" >&2
-      exit 1
+      false
+      return
       ;;
     *)
       TEMP+=("$1")
@@ -55,14 +58,15 @@ umask 0007
 if [[ "$KESSEL_SYSTEM" == "local" ]]; then
   if [[ -z "$SPACK_ROOT" ]]; then
     echo "ERROR: No active Spack installation!" >&2
-    exit 1
+    false
+    return
   else
     echo "Using Spack install at $SPACK_ROOT"
   fi
 else
   if [ ! -d "$KESSEL_WORKFLOW_DEPLOYMENT" ]; then
       unsquashfs -d "$KESSEL_WORKFLOW_DEPLOYMENT" "$KESSEL_DEPLOYMENT/.replicate.sqfs"
-      kessel_export KESSEL_PARENT_DEPLOYMENT="$KESSEL_DEPLOYMENT"
-      kessel_export KESSEL_DEPLOYMENT="$KESSEL_WORKFLOW_DEPLOYMENT"
+      kessel deploy activate "$KESSEL_WORKFLOW_DEPLOYMENT"
+      kessel system activate "$KESSEL_SYSTEM"
   fi
 fi
