cleanup shell scripts

diff --git a/libexec/kessel/workflows/pip_env/setup b/libexec/kessel/workflows/pip_env/setup
--- a/libexec/kessel/workflows/pip_env/setup
+++ b/libexec/kessel/workflows/pip_env/setup
@@ -20,8 +20,7 @@ while (( "$#" )); do
          shift 2
       else
          echo "ERROR: -S/--source-dir requires an argument." >&2
-         false
-         return
+         return 1
       fi
       ;;
     -B|--build-dir)
@@ -30,8 +29,7 @@ while (( "$#" )); do
          shift 2
       else
          echo "ERROR: -B/--build-dir requires an argument." >&2
-         false
-         return
+         return 1
       fi
       ;;
     -e|--env)
@@ -40,29 +38,24 @@ while (( "$#" )); do
          shift 2
       else
          echo "ERROR: -e/--env requires an argument." >&2
-         false
-         return
+         return 1
       fi
       ;;
     --source-dir=*)
-      value="${1#*=}"
-      export KESSEL_SOURCE_DIR="$value"
+      export KESSEL_SOURCE_DIR=${1#*=}
       shift
       ;;
     --build-dir=*)
-      value="${1#*=}"
-      export KESSEL_BUILD_DIR="$value"
+      export KESSEL_BUILD_DIR=${1#*=}
       shift
       ;;
     --env=*)
-      value="${1#*=}"
-      export KESSEL_ENVIRONMENT="$value"
+      export KESSEL_ENVIRONMENT=${1#*=}
       shift
       ;;
     -*|--*)
       echo "ERROR: invalid option $1" >&2
-      false
-      return
+      return 1
       ;;
     *)
       TEMP+=("$1")
@@ -82,9 +75,8 @@ fi
 source "$ENV/bin/activate"
 
 if [ $? -ne 0 ]; then
-    echo "Failed to activate environment"
-    false
-    return
+    echo "ERROR: Failed to activate environment" >&2
+    return 1
 fi
 
 python3 -m pip install -r "$KESSEL_REQUIREMENTS"
diff --git a/libexec/kessel/workflows/spack/prepare_env b/libexec/kessel/workflows/spack/prepare_env
--- a/libexec/kessel/workflows/spack/prepare_env
+++ b/libexec/kessel/workflows/spack/prepare_env
@@ -4,8 +4,7 @@
 
 if [ -z "$KESSEL_SYSTEM" ] || [ -z "$KESSEL_PROJECT_SPEC" ]; then
   echo "ERROR: Invalid state '$KESSEL_SYSTEM' '$KESSEL_PROJECT_SPEC' " >&2
-  false
-  return
+  return 1
 fi
 
 export KESSEL_ENVIRONMENT="${KESSEL_ENVIRONMENT:-default}"
@@ -17,7 +16,6 @@ while (( "$#" )); do
   case "$1" in
     -h|--help)
       usage
-      true
       return
       ;;
     -e|--env)
@@ -26,13 +24,11 @@ while (( "$#" )); do
          shift 2
       else
          echo "ERROR: -S/--source-dir requires an argument." >&2
-         false
-         return
+         return 1
       fi
       ;;
     --env=*)
-      value="${1#*=}"
-      export KESSEL_ENVIRONMENT="$value"
+      export KESSEL_ENVIRONMENT=${1#*=}
       shift
       ;;
     -S|--source-dir)
@@ -41,13 +37,11 @@ while (( "$#" )); do
          shift 2
       else
          echo "ERROR: -S/--source-dir requires an argument." >&2
-         false
-         return
+         return 1
       fi
       ;;
     --source-dir=*)
-      value="${1#*=}"
-      export KESSEL_INSTALL_DIR="$value"
+      export KESSEL_INSTALL_DIR=${1#*=}
       shift
       ;;
     -B|--build-dir)
@@ -56,19 +50,16 @@ while (( "$#" )); do
          shift 2
       else
          echo "ERROR: -B/--build-dir requires an argument." >&2
-         false
-         return
+         return 1
       fi
       ;;
     --build-dir=*)
-      value="${1#*=}"
-      export KESSEL_BUILD_DIR="$value"
+      export KESSEL_BUILD_DIR=${1#*=}
       shift
       ;;
     -*|--*)
       echo "ERROR: invalid option $1" >&2
-      false
-      return
+      return 1
       ;;
     *)
       TEMP="$TEMP $1"
@@ -87,9 +78,8 @@ if ! spack env activate --without-view "$KESSEL_ENVIRONMENT"; then
     spack env activate --without-view "$KESSEL_ENVIRONMENT"
     spack add "$KESSEL_PROJECT_SPEC"
   else
-    echo "ERROR: Can not activate or create environment $KESSEL_ENVIRONMENT!"
-    false
-    return
+    echo "ERROR: Can not activate or create environment $KESSEL_ENVIRONMENT!" >&2
+    return 1
   fi
 fi
 
